In [6]:
from time import sleep
for letters in "Hello, world!":
    sleep(0.25)
    print(letters, end ='')

Hello, world!

### task1

In [5]:
import numpy as np

In [9]:
a = ([1, 6], [2, 8], [3, 11], [3, 10], [1, 7])
np.array(a)

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [10]:
a_mean = np.mean(a, axis = 0, keepdims = True)
a_mean

array([[2. , 8.4]])

### task2

In [14]:
a_centered = np.subtract(a, a_mean)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### task3

In [20]:
a_centered_sp = np.dot(a_centered[0:, 0], a_centered[0:, 1])
a_centered_sp

8.0

In [24]:
rezult = a_centered_sp / (np.array(a).shape[0] - 1)
rezult

2.0

### task4

In [26]:
transp_a = np.array(a).transpose()
covar = np.cov(transp_a)
covar

array([[1. , 2. ],
       [2. , 4.3]])

или так

In [28]:
covar = np.cov(np.array(a), rowvar = False)
covar

array([[1. , 2. ],
       [2. , 4.3]])

правда я так и не понял, для чего применяется ковариация и почему ее значение равно элементу матрицы [0,1] 