In [2]:
import numpy as np
a = np.array([i for i in range(12, 24)])
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [3]:
b1 = np.reshape(a, (2, 6), order = 'C')
b2 = np.reshape(a, (3, 4), order = 'F')
b3 = np.reshape(a, (4, 3))
b4 = np.reshape(a, (6, 2))
b5 = np.reshape(a, (12, 1))

In [4]:
b1, b2, b3, b4, b5

(array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 15, 18, 21],
        [13, 16, 19, 22],
        [14, 17, 20, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]))

In [5]:
c1 = np.reshape(a, (-1, 6))
c2 = np.reshape(a, (-1, 4))
c3 = np.reshape(a, (4, -1))
c4 = np.reshape(a, (6, -1))
c5 = np.reshape(a, (12, -1))

In [6]:
c1, c2, c3, c4, c5

(array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]))

In [7]:
# 4 вопрос: это двумерный массив структуры (12, 1)
# в отличие от массива а, который является одномерным
c5.shape, a.shape

((12, 1), (12,))

In [8]:
d= np.random.uniform(2, 5, (3, 4))
d, d.size

(array([[2.0703767 , 4.00152144, 2.59039203, 4.24514414],
        [3.33232164, 4.58677375, 4.78098734, 2.21363326],
        [4.02004554, 3.58106809, 3.10376014, 4.8230081 ]]),
 12)

In [9]:
d_mono = d.reshape(1, -1)
d_mono, d_mono.size

(array([[2.0703767 , 4.00152144, 2.59039203, 4.24514414, 3.33232164,
         4.58677375, 4.78098734, 2.21363326, 4.02004554, 3.58106809,
         3.10376014, 4.8230081 ]]),
 12)

In [10]:
e_a = np.array([i for i in range(20, 1, -2)])
e_a, e_a.shape 

(array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2]), (10,))

In [11]:
e_b = np.array([i for i in range(20, 1, -2)]).reshape(1, -1)
e_b, e_b.shape
# разница e_a и e_b в том, что в первом случае это одномерный массив, а во втором - двумерный

(array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]]), (1, 10))

In [12]:
f_a = np.zeros((2, 2))
f_b = np.ones((3, 2))
f_ab = np.vstack((f_a, f_b))
f_ab, f_ab.size

(array([[0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]),
 10)

In [13]:
g_a = np.arange(12)
g_A = g_a.reshape(4, 3)
g_At = np.transpose(g_A)
g_B = np.dot(g_A, g_At)
# из g_B нельзя получить обратную матрицу, т.к. ее определитель равен "0"
g_A, g_At, g_B, g_B.shape, np.linalg.det(g_B)

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[ 0,  3,  6,  9],
        [ 1,  4,  7, 10],
        [ 2,  5,  8, 11]]),
 array([[  5,  14,  23,  32],
        [ 14,  50,  86, 122],
        [ 23,  86, 149, 212],
        [ 32, 122, 212, 302]]),
 (4, 4),
 0.0)

In [14]:
np.random.seed(42)

In [15]:
h_c = np.array([i for i in range(0, 16)])
C = h_c.reshape(4, -1)
D = C*10 + g_B
D_inv = np.linalg.inv(D)
C, g_B, D, np.linalg.det(D), np.linalg.matrix_rank(D), D_inv

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[  5,  14,  23,  32],
        [ 14,  50,  86, 122],
        [ 23,  86, 149, 212],
        [ 32, 122, 212, 302]]),
 array([[  5,  24,  43,  62],
        [ 54, 100, 146, 192],
        [103, 176, 249, 322],
        [152, 252, 352, 452]]),
 -7.685903354004529e-25,
 2,
 array([[ 1.10382344e+13,  5.26315789e-02, -3.31147031e+13,
          2.20764688e+13],
        [-8.46264636e+13,  9.38249922e+13,  6.62294063e+13,
         -7.54279349e+13],
        [ 1.36138224e+14, -1.87649984e+14, -3.31147031e+13,
          8.46264636e+13],
        [-6.25499948e+13,  9.38249922e+13,  0.00000000e+00,
         -3.12749974e+13]]))

In [16]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[1., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 0.]])

In [17]:
# как проверить, что у нас только 0 и 1?

In [19]:
np.where(D_inv, g_B, C)

array([[  5,  14,   2,  32],
       [  4,  50,  86,   7],
       [ 23,   9,  10, 212],
       [ 12, 122,  14,  15]])